---

- name: install PHP composer dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items: "{{ php_composer_deps }}"

- name: get PHP composer installer script
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
  changed_when: False

- name: install PHP composer
  shell: php /tmp/composer-installer.php --install-dir={{ php_composer_path }} --filename=composer
  args:
    creates: "{{ php_composer_path }}/composer"

- name: remove PHP composer installer script
  file:
    path: /tmp/composer-installer.php
    state: absent
  changed_when: False

- name: create cronjob to update composer
  cron:
    name: PHP composer update
    minute: 55
    hour: 4
    user: root
    job: "{{ php_composer_path }}/composer selfupdate --quiet --no-interaction"
    cron_file: php-composer-update
